### ISSUE TITLE
Comparison ERROR during ple execution on each data source

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/Hydra#14]
following ple(also reproduced on other ple analyses): 
[ple.txt](https://github.com/OHDSI/Hydra/files/4393745/ple.txt)

During execution I got following errors, could you advise, please?

stdout:
Error in ParallelLogger::clusterApply(cluster = cluster, x = subsets,  :
  Error(s) when calling function 'fun', see earlier messages for details
Calls: tryCatch ... tryCatchList -> execute -> generateDiagnostics -> <Anonymous>
Removing package from ?/usr/local/lib/R/site-library?
(as ?lib? is unspecified)

log:
2020-03-26 15:50:08	[Main thread]	ERROR	EstimationAnalysis.muh574ka	generateDiagnostics	Thread 4 returns error: "comparison (1) is possible only for atomic and list types" when using argument(s): list(analysisId

**Comment by jreps** [comment]
PLP or PLE? This seems to reference PLE stuff (ERROR	EstimationAnalysis.muh574ka	generateDiagnostics ) but is a PLP json?  PLP also doesn't use a cluster for any ATLAS generated package.

**Comment by KSadomtsev** [comment]
PLE, it was a typo, sorry.

**Comment by schuemie** [comment]
Can you verify that your target and comparator cohorts are not empty (e.g. by generating them in ATLAS, or querying your cohort table)?

**Comment by KSadomtsev** [comment]
yes, verified.
![image](https://user-images.githubusercontent.com/56290675/77885483-c3322080-726f-11ea-9f15-3c53de8d73bb.png)
![image](https://user-images.githubusercontent.com/56290675/77885887-89154e80-7270-11ea-915f-3a85761da943.png)

**Comment by konstjar** [comment]
@schuemie @anthonysena do you have any ideas? We are getting the same error on "[OHDSI Cov19] Comparative effects of HCQ in RA" PLE too.

**Comment by anthonysena** [comment]
Can you share the errorReport.txt from R that might have additional details?

**Comment by konstjar** [comment]
Hi @anthonysena 
There is no errorReport.txt file as all SQL queries were executed successfully. I have stdout log only. It's attached [stdout.txt](https://github.com/OHDSI/Hydra/files/4419620/stdout.txt)

**Comment by schuemie** [comment]
This is a known issue. Please update to the latest version of ParallelLogger:

```r
install.packages("ParallelLogger")
```

**Comment by konstjar** [comment]
Thanks, It solved the issue

**Comment by KSadomtsev** [comment]
it was solved by updating the version of ParallelLogger

**Comment by KSadomtsev** [comment]
Hi guys! After updating found another error on other ple:
Error in ParallelLogger::clusterApply(cluster = cluster, x = subsets, :  
Error(s) when calling function 'fun', see earlier messages for details  
Calls: tryCatch ... tryCatchList -> execute -> generateDiagnostics
[stdout.txt](https://github.com/OHDSI/Hydra/files/4421946/stdout.txt)

@schuemie @anthonysena do you have any ideas?

**Comment by konstjar** [comment]
And I'm getting one more after ParallelLogger fix
```
Error in `$<-.data.frame`(`*tmp*`, "analysisId", value = NA_integer_) : 
  replacement has 1 row, data has 0
Calls: tryCatch ... <Anonymous> -> lapply -> FUN -> $<- -> $<-.data.frame
Removing package from ?/usr/local/lib/R/site-library?
(as ?lib? is unspecified)
```
[stdout.txt](https://github.com/OHDSI/Hydra/files/4423216/stdout.txt)

**Comment by schuemie** [comment]
It seems like all outcome models failed to converge. Could you look at the `analysisSummary.csv` file to see why this might be? The 'target' and 'comparator' columns will tell you how many people there are in each cohort after PS adjustment, and the 'eventsTarget' and 'eventComparator' columns how many outcome events.

**Comment by konstjar** [comment]
I checked `analysisSummary.csv`:
-  'target' and 'comparator' columns are filed with values, no 0 values
- 'eventsTarget' and 'eventComparator' columns - many of them are 0 for 'eventsTarget'  or 'eventComparator'  or even both, but there are also numbers > 0.

**Comment by schuemie** [comment]
Any of the negative controls have non-zero event counts? (You can usually recognize negative controls as those having large outcome IDs)

**Comment by konstjar** [comment]
@schuemie as discussed, please find attached result file:
[estimation-analysis-results-6290.zip](https://github.com/OHDSI/Hydra/files/4437357/estimation-analysis-results-6290.1.zip)

**Comment by anthonysena** [comment]
Closing as the PLE skeleton was updated with the v0.3.0 which should address the items in this issue.
