### ISSUE TITLE
Estimation fails during diagnostics export when data is insufficient

### ISSUE THREAD

**Issue by wivern** [OHDSI/Hydra#9]
Sometimes estimation breaks with error during diagnostics export process.
The following line can raise an error when `data` is NULL:
```
colnames(data) <- SqlRender::camelCaseToSnakeCase(colnames(data))
```
And the error message is:
```
Error in `colnames<-`(`*tmp*`, value = character(0)) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

The suggestion is to add checking for NULL to avoid unexpected process exit:
```
if (!is.null(colnames(data))) {
    colnames(data) <- SqlRender::camelCaseToSnakeCase(colnames(data))
  }
```

**Comment by olga-ganina** [comment]
Hi @schuemie , when do you think it will possible to release new version with this fix?
